# Generated by Django 4.1.13 on 2025-03-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
